import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import AmplifyClientSide from '@/components/configureAmplify'
import '@aws-amplify/ui-react/styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div>
          <AmplifyClientSide />
          <Navbar />
          <div className='w-full flex min-h-screen flex-col items-center p-10'>{children}</div>
        </div>
      </body>
    </html>
  )
}
